rvm: 1.8.7
notifications:
  email:
    - fatmcgav@gmail.com
env:
  - PUPPET_VERSION=2.7.25
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.1
  - PUPPET_VERSION=3.3.1
  - PUPPET_VERSION=3.4.1