---
language: ruby
rvm: 
 - 1.8.7
 - 1.9.3
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: bundle exec rake test SPEC_OPTS="--format documentation" 
env:
  - PUPPET_VERSION="~>2.7.0"
  - PUPPET_VERSION="~>3.0.0"
  - PUPPET_VERSION="~>3.1.0"
  - PUPPET_VERSION="~>3.2.0"
  - PUPPET_VERSION="~>3.3.0"
  - PUPPET_VERSION="~>3.4.0"
  - PUPPET_VERSION="~>3.5.0"
matrix:
  allow_failures:
    - env: PUPPET_VERSION="~>3.0.0"
notifications:
  email:
    - fatmcgav@gmail.com
